# Generated by Django 4.2.2 on 2023-06-19 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_orderitem_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quanitity',
            new_name='quantity',
        ),
    ]
